"""Generate ``docs/PARITY.md`` from collected ``@pytest.mark.guarantee`` markers.

Modes:
  (default) rewrite ``docs/PARITY.md`` from the current markers.
  ``--check`` regenerate to a string and fail (exit 1) on any diff from the
    committed file, on a marker naming an unknown guarantee/host, or on a
    ``NOT_APPLICABLE`` cell that nonetheless has a claiming test (a contradiction).

CI runs ``--check`` so a claimed ✅ whose test was renamed/deleted, or a matrix doc
left stale, turns the build red — the design's honesty gate: every ✅ resolves to a
real, collected test.
"""

import json
import subprocess
import sys
import tempfile
from pathlib import Path

from tools.parity.guarantees import GUARANTEES, HOSTS, NOT_APPLICABLE

REPO = Path(__file__).resolve().parents[2]
DOC = REPO / "docs" / "PARITY.md"
_REPO_URL = "https://github.com/fu351/Doberman-Core/blob/main"

HEADER = """# Parity matrix

Generated by `python -m tools.parity.generate_parity` — **do not edit by hand.**
Each row is a security guarantee; each column a host Doberman can front.

- **✅** — a CI test proves the cell on that host (the link opens the test file).
- **◻** — not proven yet: an open, contributor-sized gap (see issues labeled `parity`).
- **—** — the host cannot express this guarantee today (see the footnotes).
"""


def collect() -> list[dict]:
    """Collect every guarantee-marker cell claim via a pytest ``--collect-only`` pass."""
    with tempfile.NamedTemporaryFile(suffix=".json", delete=False) as tmp:
        out_path = tmp.name
    proc = subprocess.run(  # noqa: S603 — fixed argv (sys.executable -m pytest), no shell, no untrusted input
        [
            sys.executable,
            "-m",
            "pytest",
            "tests",
            "--collect-only",
            "-q",
            "-p",
            "tools.parity.pytest_parity",
            f"--parity-dump={out_path}",
        ],
        cwd=REPO,
        capture_output=True,
        text=True,
    )
    if proc.returncode != 0:
        raise SystemExit(
            "parity: pytest collection failed:\n" + (proc.stdout or "") + (proc.stderr or "")
        )
    return json.loads(Path(out_path).read_text(encoding="utf-8"))


def render(cells: list[dict]) -> str:
    known_g = {k for k, _ in GUARANTEES}
    by_cell: dict[tuple[str, str], str] = {}
    errors: list[str] = []
    for c in cells:
        g, h, test = c["guarantee"], c["host"], c["test"]
        if g not in known_g or h not in HOSTS:
            errors.append(f"unknown guarantee/host in marker: {g!r} / {h!r} ({test})")
            continue
        if (g, h) in NOT_APPLICABLE:
            errors.append(f"cell ({g}, {h}) is declared N/A but has a claiming test {test}")
            continue
        by_cell.setdefault((g, h), test)
    if errors:
        raise SystemExit("PARITY ERRORS:\n" + "\n".join(errors))

    header_cells = [h.replace("-", " ").title() for h in HOSTS]
    lines = [
        HEADER,
        "| Guarantee | " + " | ".join(header_cells) + " |",
        "|---|" + "---|" * len(HOSTS),
    ]
    notes: list[str] = []
    for key, title in GUARANTEES:
        row = [title]
        for host in HOSTS:
            if (key, host) in NOT_APPLICABLE:
                notes.append(f"- **{title} — {host}:** {NOT_APPLICABLE[(key, host)]}")
                row.append("—")
            elif (key, host) in by_cell:
                fname = by_cell[(key, host)].split("::")[0]
                row.append(f"[✅]({_REPO_URL}/{fname})")
            else:
                row.append("◻")
        lines.append("| " + " | ".join(row) + " |")
    if notes:
        lines += ["", "### Footnotes (— cells)", "", *notes]
    return "\n".join(lines) + "\n"


def main() -> int:
    content = render(collect())
    if "--check" in sys.argv:
        if not DOC.exists() or DOC.read_text(encoding="utf-8") != content:
            print("docs/PARITY.md is stale — run: python -m tools.parity.generate_parity")
            return 1
        return 0
    DOC.write_text(content, encoding="utf-8")
    print(f"wrote {DOC}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
